<div class="brcr">
	<ul>
		<li><a href="{$basePath$}">Главная</a></li>
	</ul>
</div>
<h1>Учебный профиль</h1>
<h2>
Пройденные Вами курсы в учебных заведениях
</h2>

<?php if(count($this->kursy)) { ?>
	<?php 
	echo '<ul class="my_uz">';
	foreach($this->kursy as $uz) {
		echo '<li class="uz">';
		echo $this->escape($uz['uch_zaved']);
			echo '<ul class="my_uz_kursy">';
			foreach($uz['kursy'] as $kurs) {
				echo '<li class="kurs flex_sa"><div class="kurs_name">' . $this->escape($kurs['kurs']) . '</div><div class="data_okonch">' . $kurs['data_okonch'] . '</div></li>';
			}
			echo '</ul>';

		echo '</li>';
	}
	echo '</ul>';
	?>
<?php } else { ?>
	<div class="no_data">У Вас нет пройденных курсов</div>
<?php } ?>

<h2>Добавление курса</h2>
<div class="frmAddKurs yupForm">
	<div>
		<div>Учебное заведение:</div>
		<div><div name="uch_zaved_id"></div></div>
	</div>

	<div>
		<div>Пройденный курс:</div>
		<div><div name="kursy_id"></div></div>
	</div>

	<div>
		<div>Дата окончания:</div>
		<div><div name="data_okonch"></div></div>
	</div>

	<div>
		<div></div>
		<div><div class="btnAdd"></div></div>
	</div>

</div>
<link rel="stylesheet" href="/js/form.files/style.css">
<link rel="stylesheet" href="/js/grid.files/grid.css">
<script type="text/javascript" src="/js/yup-core.js"></script>
<script type="text/javascript" src="/js/yup-qt.js"></script>
<script type="text/javascript" src="/js/yup-form.js"></script>
<script type="text/javascript" src="/js/yup-grid.js"></script>
<script type="text/javascript">
$(function() {
	function qry(q,p,cb,eCb) {
      yupQuery({url:"{$basePath$}qry"})(q,p,function() {
         var o=this.evalJS(),e=o.errText; if(e) {
            if(!eCb || eCb.call(o,e)!==false) alert(e)
         } else cb.call(o)
      })
    }
	var frL='yupForm', txL='yupText', btL='yupButton', caL='yupCalendar', liL='yupList', f1=$('.frmAddKurs')[frL]({flexColumns:[{width:160}, {width:400}]})
	
	f1.find('[name=uch_zaved_id]')[liL]({key:'id', field:'uch_zaved', width:'320px', emptyText:'введите текст для поиска учебного заведения', gridConfig:{head:1, style:{width:'340px', maxHeight:'350px'}, json: {__originalFields:['id','uch_zaved','obr_uchr_tip','reiting'],
		uch_zaved: {caption:'Наименование учреждения', width:'50%'},
		obr_uchr_tip: {caption:'Тип', width:40},
		reiting: {caption:'Рейтинг', width:60}
	  }}, callback: function(ph, v, cb) {
		qry('quickFind_uch_zaved', {ph:ph, v:v}, function() {
			cb(this.__rowData)
		})
	}})[liL]('on','change', function() {
		f1[frL]('set','kursy_id','')
	})

	f1.find('[name=kursy_id]')[liL]({key:'id', field:'kurs', width:'320px', emptyText:'введите текст для поиска курса', callback: function(ph, v, cb) {
		qry('quickFind_kursy', {ph:ph, v:v, uch_zaved_id: f1[frL]('get','uch_zaved_id')}, function() {
			cb(this.__rowData)
		})
	}})

	f1.find('[name=data_okonch]')[caL]({})

	f1.find('.btnAdd')[btL]({caption:'Добавить курс'})[btL]('on','click', function() {
		f1[frL]('validate', function() {
			qry('addMyKurs', f1[frL]('getObject'), function() {
	            location.reload()
			})
		})
	})

	f1[frL]('bindJS', {__originalFields:['uch_zaved_id','kursy_id','data_okonch'],
		uch_zaved_id: {caption:'Учебное заведение', notNull:1},
		kursy_id: {caption:'Пройденный курс', notNull:1},
		data_okonch: {caption:'Дата окончания', notNull:1, defaultValue:new Date()}
	})
})
</script>
